// ---------------------------------------------------------
// This file was generated by parol.
// It is not intended for manual editing and changes will be
// lost after next build.
// ---------------------------------------------------------

use parol_runtime::id_tree::Tree;
use parol_runtime::lexer::{TokenStream, Tokenizer};
use parol_runtime::miette::Result;
#[allow(unused_imports)]
use parol_runtime::parser::{
    DFATransition, LLKParser, LookaheadDFA, ParseTreeType, ParseType, Production,
};
use std::cell::RefCell;
use std::path::Path;

use crate::parol_sandbox_grammar::ParolSandboxGrammar;
use crate::parol_sandbox_grammar_trait::ParolSandboxGrammarAuto;

use parol_runtime::lexer::tokenizer::{
    ERROR_TOKEN, NEW_LINE_TOKEN, UNMATCHABLE_TOKEN, WHITESPACE_TOKEN,
};

pub const TERMINALS: &[&str; 11] = &[
    /*  0 */ UNMATCHABLE_TOKEN,
    /*  1 */ UNMATCHABLE_TOKEN,
    /*  2 */ UNMATCHABLE_TOKEN,
    /*  3 */ UNMATCHABLE_TOKEN,
    /*  4 */ UNMATCHABLE_TOKEN,
    /*  5 */ r###"!"###,
    /*  6 */ r###"\->"###,
    /*  7 */ r###"a"###,
    /*  8 */ r###"b"###,
    /*  9 */ r###"c"###,
    /* 10 */ ERROR_TOKEN,
];

pub const TERMINAL_NAMES: &[&str; 11] = &[
    /*  0 */ "EndOfInput",
    /*  1 */ "Newline",
    /*  2 */ "Whitespace",
    /*  3 */ "LineComment",
    /*  4 */ "BlockComment",
    /*  5 */ "Bang",
    /*  6 */ "MinusGT",
    /*  7 */ "A",
    /*  8 */ "B",
    /*  9 */ "C",
    /* 10 */ "Error",
];

/* SCANNER_0: "INITIAL" */
const SCANNER_0: (&[&str; 5], &[usize; 5]) = (
    &[
        /*  0 */ UNMATCHABLE_TOKEN,
        /*  1 */ NEW_LINE_TOKEN,
        /*  2 */ WHITESPACE_TOKEN,
        /*  3 */ UNMATCHABLE_TOKEN,
        /*  4 */ UNMATCHABLE_TOKEN,
    ],
    &[
        5, /* Bang */
        6, /* MinusGT */
        7, /* A */
        8, /* B */
        9, /* C */
    ],
);

/* SCANNER_1: "String" */
const SCANNER_1: (&[&str; 5], &[usize; 0]) = (
    &[
        /*  0 */ UNMATCHABLE_TOKEN,
        /*  1 */ UNMATCHABLE_TOKEN,
        /*  2 */ UNMATCHABLE_TOKEN,
        /*  3 */ UNMATCHABLE_TOKEN,
        /*  4 */ UNMATCHABLE_TOKEN,
    ],
    &[],
);

const MAX_K: usize = 1;

pub const NON_TERMINALS: &[&str; 5] = &[
    /* 0 */ "A", /* 1 */ "B", /* 2 */ "C", /* 3 */ "Expr",
    /* 4 */ "ExprOpt",
];

pub const LOOKAHEAD_AUTOMATA: &[LookaheadDFA; 5] = &[
    /* 0 - "A" */
    LookaheadDFA {
        states: &[Some(4)],
        transitions: &[],
        k: 0,
    },
    /* 1 - "B" */
    LookaheadDFA {
        states: &[Some(5)],
        transitions: &[],
        k: 0,
    },
    /* 2 - "C" */
    LookaheadDFA {
        states: &[Some(6)],
        transitions: &[],
        k: 0,
    },
    /* 3 - "Expr" */
    LookaheadDFA {
        states: &[None, Some(0), Some(1)],
        transitions: &[DFATransition(0, 5, 2), DFATransition(0, 7, 1)],
        k: 1,
    },
    /* 4 - "ExprOpt" */
    LookaheadDFA {
        states: &[None, Some(2), Some(3)],
        transitions: &[
            DFATransition(0, 5, 2),
            DFATransition(0, 6, 1),
            DFATransition(0, 7, 2),
        ],
        k: 1,
    },
];

pub const PRODUCTIONS: &[Production; 7] = &[
    // 0 - Expr: A B C;
    Production {
        lhs: 3,
        production: &[ParseType::N(2), ParseType::N(1), ParseType::N(0)],
    },
    // 1 - Expr: '!' ExprOpt /* Option */ Expr;
    Production {
        lhs: 3,
        production: &[ParseType::N(3), ParseType::N(4), ParseType::T(5)],
    },
    // 2 - ExprOpt: '->' Expr;
    Production {
        lhs: 4,
        production: &[ParseType::N(3), ParseType::T(6)],
    },
    // 3 - ExprOpt: ;
    Production {
        lhs: 4,
        production: &[],
    },
    // 4 - A: "a";
    Production {
        lhs: 0,
        production: &[ParseType::T(7)],
    },
    // 5 - B: "b";
    Production {
        lhs: 1,
        production: &[ParseType::T(8)],
    },
    // 6 - C: "c";
    Production {
        lhs: 2,
        production: &[ParseType::T(9)],
    },
];

parol_runtime::lazy_static::lazy_static! {
    static ref TOKENIZERS: Vec<(&'static str, Tokenizer)> = vec![
        ("INITIAL", Tokenizer::build(TERMINALS, SCANNER_0.0, SCANNER_0.1).unwrap()),
        ("String", Tokenizer::build(TERMINALS, SCANNER_1.0, SCANNER_1.1).unwrap()),

    ];
}

pub fn parse<'t, T>(
    input: &'t str,
    file_name: T,
    user_actions: &mut ParolSandboxGrammar<'t>,
) -> Result<Tree<ParseTreeType<'t>>>
where
    T: AsRef<Path>,
{
    let mut llk_parser = LLKParser::new(
        3,
        LOOKAHEAD_AUTOMATA,
        PRODUCTIONS,
        TERMINAL_NAMES,
        NON_TERMINALS,
    );
    let token_stream =
        RefCell::new(TokenStream::new(input, file_name, &TOKENIZERS, MAX_K).unwrap());
    // Initialize wrapper
    let mut user_actions = ParolSandboxGrammarAuto::new(user_actions);
    let result = llk_parser.parse(token_stream, &mut user_actions);
    match result {
        Ok(()) => Ok(llk_parser.parse_tree),
        Err(e) => Err(e),
    }
}
